security_controllers:
    resource:
        
        path: ../src/Core/Infrastructure/Controller/
        namespace: App\Core\Infrastructure\Controller
    type: attribute

home_controllers:
    resource:
        path: ../src/Home/Infrastructure/Controller/
        namespace: App\Home\Infrastructure\Controller
    type: attribute